// Auto-extracted maps from lunar-go LunarUtil.go — do not edit by hand.
use std::collections::HashMap;
use std::sync::LazyLock;

pub static TIAN_SHEN_TYPE: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("青龙", "黄道");
    m.insert("明堂", "黄道");
    m.insert("金匮", "黄道");
    m.insert("天德", "黄道");
    m.insert("玉堂", "黄道");
    m.insert("司命", "黄道");
    m.insert("天刑", "黑道");
    m.insert("朱雀", "黑道");
    m.insert("白虎", "黑道");
    m.insert("天牢", "黑道");
    m.insert("玄武", "黑道");
    m.insert("勾陈", "黑道");
    m
});
pub static TIAN_SHEN_TYPE_LUCK: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("黄道", "吉");
    m.insert("黑道", "凶");
    m
});
pub static LU: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("甲", "寅");
    m.insert("乙", "卯");
    m.insert("丙", "巳");
    m.insert("丁", "午");
    m.insert("戊", "巳");
    m.insert("己", "午");
    m.insert("庚", "申");
    m.insert("辛", "酉");
    m.insert("壬", "亥");
    m.insert("癸", "子");
    m.insert("寅", "甲");
    m.insert("卯", "乙");
    m.insert("巳", "丙，戊");
    m.insert("午", "丁，己");
    m.insert("申", "庚");
    m.insert("酉", "辛");
    m.insert("亥", "壬");
    m.insert("子", "癸");
    m
});
pub static FESTIVAL: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("1-1", "春节");
    m.insert("1-15", "元宵节");
    m.insert("2-2", "龙头节");
    m.insert("5-5", "端午节");
    m.insert("7-7", "七夕节");
    m.insert("8-15", "中秋节");
    m.insert("9-9", "重阳节");
    m.insert("12-8", "腊八节");
    m
});
pub static OTHER_FESTIVAL: LazyLock<HashMap<&'static str, Vec<&'static str>>> = LazyLock::new(|| {
    let mut m: HashMap<&'static str, Vec<&'static str>> = HashMap::new();
    m.insert("1-4", vec!["接神日"]);
    m.insert("1-5", vec!["隔开日"]);
    m.insert("1-7", vec!["人日"]);
    m.insert("1-8", vec!["谷日", "顺星节"]);
    m.insert("1-9", vec!["天日"]);
    m.insert("1-10", vec!["地日"]);
    m.insert("1-20", vec!["天穿节"]);
    m.insert("1-25", vec!["填仓节"]);
    m.insert("1-30", vec!["正月晦"]);
    m.insert("2-1", vec!["中和节"]);
    m.insert("2-2", vec!["社日节"]);
    m.insert("3-3", vec!["上巳节"]);
    m.insert("5-20", vec!["分龙节"]);
    m.insert("5-25", vec!["会龙节"]);
    m.insert("6-6", vec!["天贶节"]);
    m.insert("6-24", vec!["观莲节"]);
    m.insert("6-25", vec!["五谷母节"]);
    m.insert("7-15", vec!["中元节"]);
    m.insert("7-22", vec!["财神节"]);
    m.insert("7-29", vec!["地藏节"]);
    m.insert("8-1", vec!["天灸日"]);
    m.insert("10-1", vec!["寒衣节"]);
    m.insert("10-10", vec!["十成节"]);
    m.insert("10-15", vec!["下元节"]);
    m.insert("12-7", vec!["驱傩日"]);
    m.insert("12-16", vec!["尾牙"]);
    m.insert("12-24", vec!["祭灶日"]);
    m
});
pub static XIU: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("申 1", "毕");
    m.insert("申 2", "翼");
    m.insert("申 3", "箕");
    m.insert("申 4", "奎");
    m.insert("申 5", "鬼");
    m.insert("申 6", "氐");
    m.insert("申 0", "虚");
    m.insert("子 1", "毕");
    m.insert("子 2", "翼");
    m.insert("子 3", "箕");
    m.insert("子 4", "奎");
    m.insert("子 5", "鬼");
    m.insert("子 6", "氐");
    m.insert("子 0", "虚");
    m.insert("辰 1", "毕");
    m.insert("辰 2", "翼");
    m.insert("辰 3", "箕");
    m.insert("辰 4", "奎");
    m.insert("辰 5", "鬼");
    m.insert("辰 6", "氐");
    m.insert("辰 0", "虚");
    m.insert("巳 1", "危");
    m.insert("巳 2", "觜");
    m.insert("巳 3", "轸");
    m.insert("巳 4", "斗");
    m.insert("巳 5", "娄");
    m.insert("巳 6", "柳");
    m.insert("巳 0", "房");
    m.insert("酉 1", "危");
    m.insert("酉 2", "觜");
    m.insert("酉 3", "轸");
    m.insert("酉 4", "斗");
    m.insert("酉 5", "娄");
    m.insert("酉 6", "柳");
    m.insert("酉 0", "房");
    m.insert("丑 1", "危");
    m.insert("丑 2", "觜");
    m.insert("丑 3", "轸");
    m.insert("丑 4", "斗");
    m.insert("丑 5", "娄");
    m.insert("丑 6", "柳");
    m.insert("丑 0", "房");
    m.insert("寅 1", "心");
    m.insert("寅 2", "室");
    m.insert("寅 3", "参");
    m.insert("寅 4", "角");
    m.insert("寅 5", "牛");
    m.insert("寅 6", "胃");
    m.insert("寅 0", "星");
    m.insert("午 1", "心");
    m.insert("午 2", "室");
    m.insert("午 3", "参");
    m.insert("午 4", "角");
    m.insert("午 5", "牛");
    m.insert("午 6", "胃");
    m.insert("午 0", "星");
    m.insert("戌 1", "心");
    m.insert("戌 2", "室");
    m.insert("戌 3", "参");
    m.insert("戌 4", "角");
    m.insert("戌 5", "牛");
    m.insert("戌 6", "胃");
    m.insert("戌 0", "星");
    m.insert("亥 1", "张");
    m.insert("亥 2", "尾");
    m.insert("亥 3", "壁");
    m.insert("亥 4", "井");
    m.insert("亥 5", "亢");
    m.insert("亥 6", "女");
    m.insert("亥 0", "昴");
    m.insert("卯 1", "张");
    m.insert("卯 2", "尾");
    m.insert("卯 3", "壁");
    m.insert("卯 4", "井");
    m.insert("卯 5", "亢");
    m.insert("卯 6", "女");
    m.insert("卯 0", "昴");
    m.insert("未 1", "张");
    m.insert("未 2", "尾");
    m.insert("未 3", "壁");
    m.insert("未 4", "井");
    m.insert("未 5", "亢");
    m.insert("未 6", "女");
    m.insert("未 0", "昴");
    m
});
pub static XIU_LUCK: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("角", "吉");
    m.insert("亢", "凶");
    m.insert("氐", "凶");
    m.insert("房", "吉");
    m.insert("心", "凶");
    m.insert("尾", "吉");
    m.insert("箕", "吉");
    m.insert("斗", "吉");
    m.insert("牛", "凶");
    m.insert("女", "凶");
    m.insert("虚", "凶");
    m.insert("危", "凶");
    m.insert("室", "吉");
    m.insert("壁", "吉");
    m.insert("奎", "凶");
    m.insert("娄", "吉");
    m.insert("胃", "吉");
    m.insert("昴", "凶");
    m.insert("毕", "吉");
    m.insert("觜", "凶");
    m.insert("参", "吉");
    m.insert("井", "吉");
    m.insert("鬼", "凶");
    m.insert("柳", "凶");
    m.insert("星", "凶");
    m.insert("张", "吉");
    m.insert("翼", "凶");
    m.insert("轸", "吉");
    m
});
pub static XIU_SONG: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("角", "角星造作主荣昌，外进田财及女郎，嫁娶婚姻出贵子，文人及第见君王，惟有埋葬不可用，三年之后主瘟疫，起工修筑坟基地，堂前立见主人凶。");
    m.insert("亢", "亢星造作长房当，十日之中主有殃，田地消磨官失职，接运定是虎狼伤，嫁娶婚姻用此日，儿孙新妇守空房，埋葬若还用此日，当时害祸主重伤。");
    m.insert("氐", "氐星造作主灾凶，费尽田园仓库空，埋葬不可用此日，悬绳吊颈祸重重，若是婚姻离别散，夜招浪子入房中，行船必定遭沉没，更生聋哑子孙穷。");
    m.insert("房", "房星造作田园进，钱财牛马遍山岗，更招外处田庄宅，荣华富贵福禄康，埋葬若然用此日，高官进职拜君王，嫁娶嫦娥至月殿，三年抱子至朝堂。");
    m.insert("心", "心星造作大为凶，更遭刑讼狱囚中，忤逆官非宅产退，埋葬卒暴死相从，婚姻若是用此日，子死儿亡泪满胸，三年之内连遭祸，事事教君没始终。");
    m.insert("尾", "尾星造作主天恩，富贵荣华福禄增，招财进宝兴家宅，和合婚姻贵子孙，埋葬若能依此日，男清女正子孙兴，开门放水招田宅，代代公侯远播名。");
    m.insert("箕", "箕星造作主高强，岁岁年年大吉昌，埋葬修坟大吉利，田蚕牛马遍山岗，开门放水招田宅，箧满金银谷满仓，福荫高官加禄位，六亲丰禄乐安康。");
    m.insert("斗", "斗星造作主招财，文武官员位鼎台，田宅家财千万进，坟堂修筑贵富来，开门放水招牛马，旺蚕男女主和谐，遇此吉宿来照护，时支福庆永无灾。");
    m.insert("牛", "牛星造作主灾危，九横三灾不可推，家宅不安人口退，田蚕不利主人衰，嫁娶婚姻皆自损，金银财谷渐无之，若是开门并放水，牛猪羊马亦伤悲。");
    m.insert("女", "女星造作损婆娘，兄弟相嫌似虎狼，埋葬生灾逢鬼怪，颠邪疾病主瘟惶，为事遭官财失散，泻利留连不可当，开门放水用此日，全家财散主离乡。");
    m.insert("虚", "虚星造作主灾殃，男女孤眠不一双，内乱风声无礼节，儿孙媳妇伴人床，开门放水遭灾祸，虎咬蛇伤又卒亡，三三五五连年病，家破人亡不可当。");
    m.insert("危", "危星不可造高楼，自遭刑吊见血光，三年孩子遭水厄，后生出外永不还，埋葬若还逢此日，周年百日取高堂，三年两载一悲伤，开门放水到官堂。");
    m.insert("室", "室星修造进田牛，儿孙代代近王侯，家贵荣华天上至，寿如彭祖八千秋，开门放水招财帛，和合婚姻生贵儿，埋葬若能依此日，门庭兴旺福无休。");
    m.insert("壁", "壁星造作主增财，丝蚕大熟福滔天，奴婢自来人口进，开门放水出英贤，埋葬招财官品进，家中诸事乐陶然，婚姻吉利主贵子，早播名誉著祖鞭。");
    m.insert("奎", "奎星造作得祯祥，家内荣和大吉昌，若是埋葬阴卒死，当年定主两三伤，看看军令刑伤到，重重官事主瘟惶，开门放水遭灾祸，三年两次损儿郎。");
    m.insert("娄", "娄星修造起门庭，财旺家和事事兴，外进钱财百日进，一家兄弟播高名，婚姻进益生贵子，玉帛金银箱满盈，放水开门皆吉利，男荣女贵寿康宁。");
    m.insert("胃", "胃星造作事如何，家贵荣华喜气多，埋葬贵临官禄位，夫妇齐眉永保康，婚姻遇此家富贵，三灾九祸不逢他，从此门前多吉庆，儿孙代代拜金阶。");
    m.insert("昴", "昴星造作进田牛，埋葬官灾不得休，重丧二日三人死，尽卖田园不记增，开门放水招灾祸，三岁孩儿白了头，婚姻不可逢此日，死别生离是可愁。");
    m.insert("毕", "毕星造作主光前，买得田园有余钱，埋葬此日添官职，田蚕大熟永丰年，开门放水多吉庆，合家人口得安然，婚姻若得逢此日，生得孩儿福寿全。");
    m.insert("觜", "觜星造作有徒刑，三年必定主伶丁，埋葬卒死多因此，取定寅年使杀人，三丧不止皆由此，一人药毒二人身，家门田地皆退败，仓库金银化作尘。");
    m.insert("参", "参星造作旺人家，文星照耀大光华，只因造作田财旺，埋葬招疾哭黄沙，开门放水加官职，房房子孙见田加，婚姻许遁遭刑克，男女朝开幕落花。");
    m.insert("井", "井星造作旺蚕田，金榜题名第一光，埋葬须防惊卒死，狂颠风疾入黄泉，开门放水招财帛，牛马猪羊旺莫言，贵人田塘来入宅，儿孙兴旺有余钱。");
    m.insert("鬼", "鬼星起造卒人亡，堂前不见主人郎，埋葬此日官禄至，儿孙代代近君王，开门放水须伤死，嫁娶夫妻不久长，修土筑墙伤产女，手扶双女泪汪汪。");
    m.insert("柳", "柳星造作主遭官，昼夜偷闭不暂安，埋葬瘟惶多疾病，田园退尽守冬寒，开门放水遭聋瞎，腰驼背曲似弓弯，更有棒刑宜谨慎，妇人随客走盘桓。");
    m.insert("星", "星宿日好造新房，进职加官近帝王，不可埋葬并放水，凶星临位女人亡，生离死别无心恋，要自归休别嫁郎，孔子九曲殊难度，放水开门天命伤。");
    m.insert("张", "张星日好造龙轩，年年并见进庄田，埋葬不久升官职，代代为官近帝前，开门放水招财帛，婚姻和合福绵绵，田蚕人满仓库满，百般顺意自安然。");
    m.insert("翼", "翼星不利架高堂，三年二载见瘟惶，埋葬若还逢此日，子孙必定走他乡，婚姻此日不宜利，归家定是不相当，开门放水家须破，少女恋花贪外郎。");
    m.insert("轸", "轸星临水造龙宫，代代为官受皇封，富贵荣华增寿禄，库满仓盈自昌隆，埋葬文昌来照助，宅舍安宁不见凶，更有为官沾帝宠，婚姻龙子入龙宫。");
    m
});
pub static SHOU: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("东", "青龙");
    m.insert("南", "朱雀");
    m.insert("西", "白虎");
    m.insert("北", "玄武");
    m
});
pub static SHA: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("子", "南");
    m.insert("丑", "东");
    m.insert("寅", "北");
    m.insert("卯", "西");
    m.insert("辰", "南");
    m.insert("巳", "东");
    m.insert("午", "北");
    m.insert("未", "西");
    m.insert("申", "南");
    m.insert("酉", "东");
    m.insert("戌", "北");
    m.insert("亥", "西");
    m
});
pub static POSITION_DESC: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("坎", "正北");
    m.insert("艮", "东北");
    m.insert("震", "正东");
    m.insert("巽", "东南");
    m.insert("离", "正南");
    m.insert("坤", "西南");
    m.insert("兑", "正西");
    m.insert("乾", "西北");
    m.insert("中", "中宫");
    m
});
pub static GONG: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("角", "东");
    m.insert("井", "南");
    m.insert("奎", "西");
    m.insert("斗", "北");
    m.insert("亢", "东");
    m.insert("鬼", "南");
    m.insert("娄", "西");
    m.insert("牛", "北");
    m.insert("氐", "东");
    m.insert("柳", "南");
    m.insert("胃", "西");
    m.insert("女", "北");
    m.insert("房", "东");
    m.insert("星", "南");
    m.insert("昴", "西");
    m.insert("虚", "北");
    m.insert("心", "东");
    m.insert("张", "南");
    m.insert("毕", "西");
    m.insert("危", "北");
    m.insert("尾", "东");
    m.insert("翼", "南");
    m.insert("觜", "西");
    m.insert("室", "北");
    m.insert("箕", "东");
    m.insert("轸", "南");
    m.insert("参", "西");
    m.insert("壁", "北");
    m
});
pub static ZHENG: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("角", "木");
    m.insert("井", "木");
    m.insert("奎", "木");
    m.insert("斗", "木");
    m.insert("亢", "金");
    m.insert("鬼", "金");
    m.insert("娄", "金");
    m.insert("牛", "金");
    m.insert("氐", "土");
    m.insert("柳", "土");
    m.insert("胃", "土");
    m.insert("女", "土");
    m.insert("房", "日");
    m.insert("星", "日");
    m.insert("昴", "日");
    m.insert("虚", "日");
    m.insert("心", "月");
    m.insert("张", "月");
    m.insert("毕", "月");
    m.insert("危", "月");
    m.insert("尾", "火");
    m.insert("翼", "火");
    m.insert("觜", "火");
    m.insert("室", "火");
    m.insert("箕", "水");
    m.insert("轸", "水");
    m.insert("参", "水");
    m.insert("壁", "水");
    m
});
pub static ANIMAL: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("角", "蛟");
    m.insert("斗", "獬");
    m.insert("奎", "狼");
    m.insert("井", "犴");
    m.insert("亢", "龙");
    m.insert("牛", "牛");
    m.insert("娄", "狗");
    m.insert("鬼", "羊");
    m.insert("女", "蝠");
    m.insert("氐", "貉");
    m.insert("胃", "彘");
    m.insert("柳", "獐");
    m.insert("房", "兔");
    m.insert("虚", "鼠");
    m.insert("昴", "鸡");
    m.insert("星", "马");
    m.insert("心", "狐");
    m.insert("危", "燕");
    m.insert("毕", "乌");
    m.insert("张", "鹿");
    m.insert("尾", "虎");
    m.insert("室", "猪");
    m.insert("觜", "猴");
    m.insert("翼", "蛇");
    m.insert("箕", "豹");
    m.insert("壁", "獝");
    m.insert("参", "猿");
    m.insert("轸", "蚓");
    m
});
pub static WU_XING_GAN: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("甲", "木");
    m.insert("乙", "木");
    m.insert("丙", "火");
    m.insert("丁", "火");
    m.insert("戊", "土");
    m.insert("己", "土");
    m.insert("庚", "金");
    m.insert("辛", "金");
    m.insert("壬", "水");
    m.insert("癸", "水");
    m
});
pub static WU_XING_ZHI: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("寅", "木");
    m.insert("卯", "木");
    m.insert("巳", "火");
    m.insert("午", "火");
    m.insert("辰", "土");
    m.insert("丑", "土");
    m.insert("戌", "土");
    m.insert("未", "土");
    m.insert("申", "金");
    m.insert("酉", "金");
    m.insert("亥", "水");
    m.insert("子", "水");
    m
});
pub static NAYIN: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("甲子", "海中金");
    m.insert("甲午", "沙中金");
    m.insert("丙寅", "炉中火");
    m.insert("丙申", "山下火");
    m.insert("戊辰", "大林木");
    m.insert("戊戌", "平地木");
    m.insert("庚午", "路旁土");
    m.insert("庚子", "壁上土");
    m.insert("壬申", "剑锋金");
    m.insert("壬寅", "金箔金");
    m.insert("甲戌", "山头火");
    m.insert("甲辰", "覆灯火");
    m.insert("丙子", "涧下水");
    m.insert("丙午", "天河水");
    m.insert("戊寅", "城头土");
    m.insert("戊申", "大驿土");
    m.insert("庚辰", "白蜡金");
    m.insert("庚戌", "钗钏金");
    m.insert("壬午", "杨柳木");
    m.insert("壬子", "桑柘木");
    m.insert("甲申", "泉中水");
    m.insert("甲寅", "大溪水");
    m.insert("丙戌", "屋上土");
    m.insert("丙辰", "沙中土");
    m.insert("戊子", "霹雳火");
    m.insert("戊午", "天上火");
    m.insert("庚寅", "松柏木");
    m.insert("庚申", "石榴木");
    m.insert("壬辰", "长流水");
    m.insert("壬戌", "大海水");
    m.insert("乙丑", "海中金");
    m.insert("乙未", "沙中金");
    m.insert("丁卯", "炉中火");
    m.insert("丁酉", "山下火");
    m.insert("己巳", "大林木");
    m.insert("己亥", "平地木");
    m.insert("辛未", "路旁土");
    m.insert("辛丑", "壁上土");
    m.insert("癸酉", "剑锋金");
    m.insert("癸卯", "金箔金");
    m.insert("乙亥", "山头火");
    m.insert("乙巳", "覆灯火");
    m.insert("丁丑", "涧下水");
    m.insert("丁未", "天河水");
    m.insert("己卯", "城头土");
    m.insert("己酉", "大驿土");
    m.insert("辛巳", "白蜡金");
    m.insert("辛亥", "钗钏金");
    m.insert("癸未", "杨柳木");
    m.insert("癸丑", "桑柘木");
    m.insert("乙酉", "泉中水");
    m.insert("乙卯", "大溪水");
    m.insert("丁亥", "屋上土");
    m.insert("丁巳", "沙中土");
    m.insert("己丑", "霹雳火");
    m.insert("己未", "天上火");
    m.insert("辛卯", "松柏木");
    m.insert("辛酉", "石榴木");
    m.insert("癸巳", "长流水");
    m.insert("癸亥", "大海水");
    m
});
pub static SHI_SHEN: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("甲甲", "比肩");
    m.insert("甲乙", "劫财");
    m.insert("甲丙", "食神");
    m.insert("甲丁", "伤官");
    m.insert("甲戊", "偏财");
    m.insert("甲己", "正财");
    m.insert("甲庚", "七杀");
    m.insert("甲辛", "正官");
    m.insert("甲壬", "偏印");
    m.insert("甲癸", "正印");
    m.insert("乙乙", "比肩");
    m.insert("乙甲", "劫财");
    m.insert("乙丁", "食神");
    m.insert("乙丙", "伤官");
    m.insert("乙己", "偏财");
    m.insert("乙戊", "正财");
    m.insert("乙辛", "七杀");
    m.insert("乙庚", "正官");
    m.insert("乙癸", "偏印");
    m.insert("乙壬", "正印");
    m.insert("丙丙", "比肩");
    m.insert("丙丁", "劫财");
    m.insert("丙戊", "食神");
    m.insert("丙己", "伤官");
    m.insert("丙庚", "偏财");
    m.insert("丙辛", "正财");
    m.insert("丙壬", "七杀");
    m.insert("丙癸", "正官");
    m.insert("丙甲", "偏印");
    m.insert("丙乙", "正印");
    m.insert("丁丁", "比肩");
    m.insert("丁丙", "劫财");
    m.insert("丁己", "食神");
    m.insert("丁戊", "伤官");
    m.insert("丁辛", "偏财");
    m.insert("丁庚", "正财");
    m.insert("丁癸", "七杀");
    m.insert("丁壬", "正官");
    m.insert("丁乙", "偏印");
    m.insert("丁甲", "正印");
    m.insert("戊戊", "比肩");
    m.insert("戊己", "劫财");
    m.insert("戊庚", "食神");
    m.insert("戊辛", "伤官");
    m.insert("戊壬", "偏财");
    m.insert("戊癸", "正财");
    m.insert("戊甲", "七杀");
    m.insert("戊乙", "正官");
    m.insert("戊丙", "偏印");
    m.insert("戊丁", "正印");
    m.insert("己己", "比肩");
    m.insert("己戊", "劫财");
    m.insert("己辛", "食神");
    m.insert("己庚", "伤官");
    m.insert("己癸", "偏财");
    m.insert("己壬", "正财");
    m.insert("己乙", "七杀");
    m.insert("己甲", "正官");
    m.insert("己丁", "偏印");
    m.insert("己丙", "正印");
    m.insert("庚庚", "比肩");
    m.insert("庚辛", "劫财");
    m.insert("庚壬", "食神");
    m.insert("庚癸", "伤官");
    m.insert("庚甲", "偏财");
    m.insert("庚乙", "正财");
    m.insert("庚丙", "七杀");
    m.insert("庚丁", "正官");
    m.insert("庚戊", "偏印");
    m.insert("庚己", "正印");
    m.insert("辛辛", "比肩");
    m.insert("辛庚", "劫财");
    m.insert("辛癸", "食神");
    m.insert("辛壬", "伤官");
    m.insert("辛乙", "偏财");
    m.insert("辛甲", "正财");
    m.insert("辛丁", "七杀");
    m.insert("辛丙", "正官");
    m.insert("辛己", "偏印");
    m.insert("辛戊", "正印");
    m.insert("壬壬", "比肩");
    m.insert("壬癸", "劫财");
    m.insert("壬甲", "食神");
    m.insert("壬乙", "伤官");
    m.insert("壬丙", "偏财");
    m.insert("壬丁", "正财");
    m.insert("壬戊", "七杀");
    m.insert("壬己", "正官");
    m.insert("壬庚", "偏印");
    m.insert("壬辛", "正印");
    m.insert("癸癸", "比肩");
    m.insert("癸壬", "劫财");
    m.insert("癸乙", "食神");
    m.insert("癸甲", "伤官");
    m.insert("癸丁", "偏财");
    m.insert("癸丙", "正财");
    m.insert("癸己", "七杀");
    m.insert("癸戊", "正官");
    m.insert("癸辛", "偏印");
    m.insert("癸庚", "正印");
    m
});
pub static ZHI_HIDE_GAN: LazyLock<HashMap<&'static str, Vec<&'static str>>> = LazyLock::new(|| {
    let mut m: HashMap<&'static str, Vec<&'static str>> = HashMap::new();
    m.insert("子", vec!["癸"]);
    m.insert("丑", vec!["己", "癸", "辛"]);
    m.insert("寅", vec!["甲", "丙", "戊"]);
    m.insert("卯", vec!["乙"]);
    m.insert("辰", vec!["戊", "乙", "癸"]);
    m.insert("巳", vec!["丙", "庚", "戊"]);
    m.insert("午", vec!["丁", "己"]);
    m.insert("未", vec!["己", "丁", "乙"]);
    m.insert("申", vec!["庚", "壬", "戊"]);
    m.insert("酉", vec!["辛"]);
    m.insert("戌", vec!["戊", "辛", "丁"]);
    m.insert("亥", vec!["壬", "甲"]);
    m
});