pub static FESTIVAL: LazyLock<HashMap<&'static str, Vec<Vec<&'static str>>>> = LazyLock::new(|| {
    let mut m: HashMap<&'static str, Vec<Vec<&'static str>>> = HashMap::new();
    m.insert("1-1", vec![vec!["天腊，玉帝校世人神气禄命"]]);
    m.insert("1-3", vec![vec!["万神都会"]]);
    m.insert("1-5", vec![vec!["五虚忌"]]);
    m.insert("1-6", vec![vec!["六耗忌"]]);
    m.insert("1-7", vec![vec!["上会日"]]);
    m.insert("1-8", vec![vec!["五殿阎罗天子诞"]]);
    m.insert("1-9", vec![vec!["玉皇上帝诞"]]);
    m.insert("1-13", vec![]);
    m.insert("1-14", vec![vec!["三元降"]]);
    m.insert("1-15", vec![vec!["三元降"], vec!["上元神会"]]);
    m.insert("1-16", vec![vec!["三元降"]]);
    m.insert("1-19", vec![vec!["长春真人诞"]]);
    m.insert("1-23", vec![vec!["三尸神奏事"]]);
    m.insert("1-25", vec![vec!["天地仓开日"], vec!["犯者损寿，子带疾"]]);
    m
});
pub static OTHER_FESTIVAL: LazyLock<HashMap<&'static str, Vec<&'static str>>> = LazyLock::new(|| { let mut m: HashMap<&'static str, Vec<&'static str>> = HashMap::new();
    m.insert("1-1", vec!["弥勒菩萨圣诞"]);
    m.insert("1-6", vec!["定光佛圣诞"]);
    m.insert("2-8", vec!["释迦牟尼佛出家"]);
    m.insert("2-15", vec!["释迦牟尼佛涅槃"]);
    m.insert("2-19", vec!["观世音菩萨圣诞"]);
    m.insert("2-21", vec!["普贤菩萨圣诞"]);
    m.insert("3-16", vec!["准提菩萨圣诞"]);
    m.insert("4-4", vec!["文殊菩萨圣诞"]);
    m.insert("4-8", vec!["释迦牟尼佛圣诞"]);
    m.insert("4-15", vec!["佛吉祥日"]);
    m.insert("4-28", vec!["药王菩萨圣诞"]);
    m.insert("5-13", vec!["伽蓝菩萨圣诞"]);
    m.insert("6-3", vec!["韦驮菩萨圣诞"]);
    m.insert("6-19", vec!["观音菩萨成道"]);
    m.insert("7-13", vec!["大势至菩萨圣诞"]);
    m.insert("7-15", vec!["佛欢喜日"]);
    m.insert("7-24", vec!["龙树菩萨圣诞"]);
    m.insert("7-30", vec!["地藏菩萨圣诞"]);
    m.insert("8-15", vec!["月光菩萨圣诞"]);
    m.insert("8-22", vec!["燃灯佛圣诞"]);
    m.insert("9-9", vec!["摩利支天菩萨圣诞"]);
    m.insert("9-19", vec!["观世音菩萨出家"]);
    m.insert("9-30", vec!["药师琉璃光佛圣诞"]);
    m.insert("10-5", vec!["达摩祖师圣诞"]);
    m.insert("10-20", vec!["文殊菩萨出家"]);
    m.insert("11-17", vec!["阿弥陀佛圣诞"]);
    m.insert("11-19", vec!["日光菩萨圣诞"]);
    m.insert("12-8", vec!["释迦牟尼佛成道"]);
    m.insert("12-23", vec!["监斋菩萨圣诞"]);
    m.insert("12-29", vec!["华严菩萨圣诞"]);
    m });
