use std::collections::HashMap;
use std::sync::LazyLock;
pub static BA_HUI: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| { let mut m = HashMap::new();
    m.insert("丙午", "天会");
    m.insert("壬午", "地会");
    m.insert("壬子", "人会");
    m.insert("庚午", "日会");
    m.insert("庚申", "月会");
    m.insert("辛酉", "星辰会");
    m.insert("甲辰", "五行会");
    m.insert("甲戌", "四时会");
    m });
pub static BA_JIE: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| { let mut m = HashMap::new();
    m.insert("立春", "东北方度仙上圣天尊同梵炁始青天君下降");
    m.insert("春分", "东方玉宝星上天尊同青帝九炁天君下降");
    m.insert("立夏", "东南方好生度命天尊同梵炁始丹天君下降");
    m.insert("夏至", "南方玄真万福天尊同赤帝三炁天君下降");
    m.insert("立秋", "西南方太灵虚皇天尊同梵炁始素天君下降");
    m.insert("秋分", "西方太妙至极天尊同白帝七炁天君下降");
    m.insert("立冬", "西北方无量太华天尊同梵炁始玄天君下降");
    m.insert("冬至", "北方玄上玉宸天尊同黑帝五炁天君下降");
    m });
pub static FESTIVAL: LazyLock<HashMap<&'static str, Vec<Vec<&'static str>>>> = LazyLock::new(|| {
    let mut m: HashMap<&'static str, Vec<Vec<&'static str>>> = HashMap::new();
    m.insert("1-1", vec![vec!["天腊之辰", "天腊，此日五帝会于东方九炁青天"]]);
    m.insert("1-3", vec![vec!["郝真人圣诞"], vec!["孙真人圣诞"]]);
    m.insert("1-5", vec![vec!["孙祖清静元君诞"]]);
    m.insert("1-7", vec![vec!["举迁赏会", "此日上元赐福，天官同地水二官考校罪福"]]);
    m.insert("1-9", vec![vec!["玉皇上帝圣诞"]]);
    m.insert("1-13", vec![vec!["关圣帝君飞升"]]);
    m.insert("1-15", vec![vec!["上元天官圣诞"], vec!["老祖天师圣诞"]]);
    m.insert("1-19", vec![vec!["长春邱真人(邱处机)圣诞"]]);
    m.insert("1-28", vec![vec!["许真君(许逊天师)圣诞"]]);
    m.insert("2-1", vec![vec!["勾陈天皇大帝圣诞"], vec!["长春刘真人(刘渊然)圣诞"]]);
    m.insert("2-2", vec![vec!["土地正神诞"], vec!["姜太公圣诞"]]);
    m.insert("2-3", vec![vec!["文昌梓潼帝君圣诞"]]);
    m.insert("2-6", vec![vec!["东华帝君圣诞"]]);
    m.insert("2-13", vec![vec!["度人无量葛真君圣诞"]]);
    m.insert("2-15", vec![vec!["太清道德天尊(太上老君)圣诞"]]);
    m.insert("2-19", vec![vec!["慈航真人圣诞"]]);
    m.insert("3-1", vec![vec!["谭祖(谭处端)长真真人圣诞"]]);
    m.insert("3-3", vec![vec!["玄天上帝圣诞"]]);
    m.insert("3-6", vec![vec!["眼光娘娘圣诞"]]);
    m.insert("3-15", vec![vec!["天师张大真人圣诞"], vec!["财神赵公元帅圣诞"]]);
    m.insert("3-16", vec![vec!["三茅真君得道之辰"], vec!["中岳大帝圣诞"]]);
    m.insert("3-18", vec![vec!["王祖(王处一)玉阳真人圣诞"], vec!["后土娘娘圣诞"]]);
    m.insert("3-19", vec![vec!["太阳星君圣诞"]]);
    m.insert("3-20", vec![vec!["子孙娘娘圣诞"]]);
    m.insert("3-23", vec![vec!["天后妈祖圣诞"]]);
    m.insert("3-26", vec![vec!["鬼谷先师诞"]]);
    m.insert("3-28", vec![vec!["东岳大帝圣诞"]]);
    m.insert("4-1", vec![vec!["长生谭真君成道之辰"]]);
    m.insert("4-10", vec![vec!["何仙姑圣诞"]]);
    m.insert("4-14", vec![vec!["吕祖纯阳祖师圣诞"]]);
    m.insert("4-15", vec![vec!["钟离祖师圣诞"]]);
    m.insert("4-18", vec![vec!["北极紫微大帝圣诞"], vec!["泰山圣母碧霞元君诞"], vec!["华佗神医先师诞"]]);
    m.insert("4-20", vec![vec!["眼光圣母娘娘诞"]]);
    m.insert("4-28", vec![vec!["神农先帝诞"]]);
    m.insert("5-1", vec![vec!["南极长生大帝圣诞"]]);
    m.insert("5-5", vec![vec!["地腊之辰", "地腊，此日五帝会于南方三炁丹天"], vec!["南方雷祖圣诞"], vec!["地祗温元帅圣诞"], vec!["雷霆邓天君圣诞"]]);
    m.insert("5-11", vec![vec!["城隍爷圣诞"]]);
    m.insert("5-13", vec![vec!["关圣帝君降神"], vec!["关平太子圣诞"]]);
    m.insert("5-18", vec![vec!["张天师圣诞"]]);
    m.insert("5-20", vec![vec!["马祖丹阳真人圣诞"]]);
    m.insert("5-29", vec![vec!["紫青白祖师圣诞"]]);
    m.insert("6-1", vec![vec!["南斗星君下降"]]);
    m.insert("6-2", vec![vec!["南斗星君下降"]]);
    m.insert("6-3", vec![vec!["南斗星君下降"]]);
    m.insert("6-4", vec![vec!["南斗星君下降"]]);
    m.insert("6-5", vec![vec!["南斗星君下降"]]);
    m.insert("6-6", vec![vec!["南斗星君下降"]]);
    m.insert("6-10", vec![vec!["刘海蟾祖师圣诞"]]);
    m.insert("6-15", vec![vec!["灵官王天君圣诞"]]);
    m.insert("6-19", vec![vec!["慈航(观音)成道日"]]);
    m.insert("6-23", vec![vec!["火神圣诞"]]);
    m.insert("6-24", vec![vec!["南极大帝中方雷祖圣诞"], vec!["关圣帝君圣诞"]]);
    m.insert("6-26", vec![vec!["二郎真君圣诞"]]);
    m.insert("7-7", vec![vec!["道德腊之辰", "道德腊，此日五帝会于西方七炁素天"], vec!["庆生中会", "此日中元赦罪，地官同天水二官考校罪福"]]);
    m.insert("7-12", vec![vec!["西方雷祖圣诞"]]);
    m.insert("7-15", vec![vec!["中元地官大帝圣诞"]]);
    m.insert("7-18", vec![vec!["王母娘娘圣诞"]]);
    m.insert("7-20", vec![vec!["刘祖(刘处玄)长生真人圣诞"]]);
    m.insert("7-22", vec![vec!["财帛星君文财神增福相公李诡祖圣诞"]]);
    m.insert("7-26", vec![vec!["张三丰祖师圣诞"]]);
    m.insert("8-1", vec![vec!["许真君飞升日"]]);
    m.insert("8-3", vec![vec!["九天司命灶君诞"]]);
    m.insert("8-5", vec![vec!["北方雷祖圣诞"]]);
    m.insert("8-10", vec![vec!["北岳大帝诞辰"]]);
    m.insert("8-15", vec![vec!["太阴星君诞"]]);
    m.insert("9-1", vec![vec!["北斗九皇降世之辰"]]);
    m.insert("9-2", vec![vec!["北斗九皇降世之辰"]]);
    m.insert("9-3", vec![vec!["北斗九皇降世之辰"]]);
    m.insert("9-4", vec![vec!["北斗九皇降世之辰"]]);
    m.insert("9-5", vec![vec!["北斗九皇降世之辰"]]);
    m.insert("9-6", vec![vec!["北斗九皇降世之辰"]]);
    m.insert("9-7", vec![vec!["北斗九皇降世之辰"]]);
    m.insert("9-8", vec![vec!["北斗九皇降世之辰"]]);
    m.insert("9-9", vec![vec!["北斗九皇降世之辰"], vec!["斗姥元君圣诞"], vec!["重阳帝君圣诞"], vec!["玄天上帝飞升"], vec!["酆都大帝圣诞"]]);
    m.insert("9-22", vec![vec!["增福财神诞"]]);
    m.insert("9-23", vec![vec!["萨翁真君圣诞"]]);
    m.insert("9-28", vec![vec!["五显灵官马元帅圣诞"]]);
    m.insert("10-1", vec![vec!["民岁腊之辰", "民岁腊，此日五帝会于北方五炁黑天"], vec!["东皇大帝圣诞"]]);
    m.insert("10-3", vec![vec!["三茅应化真君圣诞"]]);
    m.insert("10-6", vec![vec!["天曹诸司五岳五帝圣诞"]]);
    m.insert("10-15", vec![vec!["下元水官大帝圣诞"], vec!["建生大会", "此日下元解厄，水官同天地二官考校罪福"]]);
    m.insert("10-18", vec![vec!["地母娘娘圣诞"]]);
    m.insert("10-19", vec![vec!["长春邱真君飞升"]]);
    m.insert("10-20", vec![vec!["虚靖天师(即三十代天师弘悟张真人)诞"]]);
    m.insert("11-6", vec![vec!["西岳大帝圣诞"]]);
    m.insert("11-9", vec![vec!["湘子韩祖圣诞"]]);
    m.insert("11-11", vec![vec!["太乙救苦天尊圣诞"]]);
    m.insert("11-26", vec![vec!["北方五道圣诞"]]);
    m.insert("12-8", vec![vec!["王侯腊之辰", "王侯腊，此日五帝会于上方玄都玉京"]]);
    m.insert("12-16", vec![vec!["南岳大帝圣诞"], vec!["福德正神诞"]]);
    m.insert("12-20", vec![vec!["鲁班先师圣诞"]]);
    m.insert("12-21", vec![vec!["天猷上帝圣诞"]]);
    m.insert("12-22", vec![vec!["重阳祖师圣诞"]]);
    m.insert("12-23", vec![vec!["祭灶王", "最适宜谢旧年太岁，开启拜新年太岁"]]);
    m.insert("12-25", vec![vec!["玉帝巡天"], vec!["天神下降"]]);
    m.insert("12-29", vec![vec!["清静孙真君(孙不二)成道"]]);
    m
});
